# Generated by Django 5.1.4 on 2025-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=100, null=True)),
                ('article_date', models.DateField(blank=True, null=True)),
                ('article_desc', models.TextField(blank=True, null=True)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='articles')),
            ],
        ),
    ]
