# Generated by Django 5.1.4 on 2025-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_author', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_price', models.IntegerField(blank=True, null=True)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='offers')),
            ],
        ),
    ]
