# Generated by Django 5.1.4 on 2025-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0002_offersmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersmodel',
            name='offer_name',
        ),
        migrations.AddField(
            model_name='offersmodel',
            name='ffer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
