# Generated by Django 5.1.4 on 2025-02-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0003_remove_offersmodel_offer_name_offersmodel_ffer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersmodel',
            old_name='ffer_name',
            new_name='offer_name',
        ),
    ]
