# Generated by Django 5.1.4 on 2025-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0004_rename_ffer_name_offersmodel_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersmodel',
            name='offer_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
