# Generated by Django 5.1.4 on 2025-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0005_offersmodel_offer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersmodel',
            name='prev_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
