# Generated by Django 5.1.4 on 2025-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0006_offersmodel_prev_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersmodel',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='prev_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True),
        ),
    ]
