# Generated by Django 5.1.4 on 2025-02-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0009_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='fifthapp.categorymodel'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
