# Generated by Django 5.1.4 on 2025-02-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0011_booksmodel_best_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
