# Generated by Django 5.1.4 on 2025-02-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0013_booksmodel_stock_cartmodel_wishlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='stock_status',
        ),
    ]
