# Generated by Django 5.1.4 on 2025-02-12 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0015_ordermodel_orderitemmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together={('user', 'book')},
        ),
    ]
