# Generated by Django 5.1.4 on 2025-02-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
