# Generated by Django 5.1.4 on 2025-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifthapp', '0018_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
